# Generated by Django 2.0.5 on 2018-07-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('craftbox', '0003_auto_20180716_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CraftboxCategory',
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'post CraftboxCategory', 'verbose_name_plural': 'post categories'},
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='CraftboxCategory',
        ),
    ]
