# Generated by Django 2.0.5 on 2018-07-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftbox', '0004_auto_20180716_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftboxcategory',
            options={'verbose_name': 'Craftbox Category', 'verbose_name_plural': 'craftbox Categories'},
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='CraftboxCategory',
            new_name='Category',
        ),
    ]
