# Generated by Django 2.0.5 on 2018-07-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftbox', '0005_auto_20180717_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crafthome',
            name='featured_post',
        ),
    ]
