# Generated by Django 2.0.5 on 2018-07-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftbox', '0010_auto_20180718_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='craftboxcategory',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
