# Generated by Django 2.0.5 on 2018-07-18 06:06

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('craftbox', '0011_auto_20180718_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='Category',
        ),
        migrations.AlterField(
            model_name='craftpost',
            name='post_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='craftbox.CraftboxCategory'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
