# Generated by Django 2.0.5 on 2018-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftbox', '0012_auto_20180718_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='crafthome',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
