# Generated by Django 2.0.5 on 2018-07-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftbox', '0014_auto_20180723_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftpost',
            name='post_category',
        ),
        migrations.AddField(
            model_name='craftpost',
            name='post_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='craftbox.CraftboxCategory'),
        ),
    ]
