# Generated by Django 2.0.5 on 2018-07-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='brand_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='site_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='brand name'),
        ),
    ]
