# Generated by Django 2.0.5 on 2018-07-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180706_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebranding',
            name='brand_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
