# Generated by Django 2.0.5 on 2018-07-01 01:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('core', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('banner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Banner')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('first_button_content', models.CharField(blank=True, max_length=55, null=True)),
                ('second_button_content', models.CharField(blank=True, max_length=55, null=True)),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_hero', to='studio.About')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.banner',),
        ),
    ]
