# Generated by Django 2.0.5 on 2018-07-01 02:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_about_abouthero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'hero'},
        ),
        migrations.AddField(
            model_name='about',
            name='process',
            field=wagtail.core.fields.StreamField([('process', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('process', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('icon', wagtail.core.blocks.CharBlock(help_text='icon must be a UNICODE character')), ('message', wagtail.core.blocks.TextBlock(rows=2))], label='our processes')))]))], blank=True),
        ),
    ]
