# Generated by Django 2.0.5 on 2018-07-01 03:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20180701_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=wagtail.core.fields.StreamField([('process', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('process', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('icon', wagtail.core.blocks.CharBlock(help_text='icon must be a UNICODE character')), ('message', wagtail.core.blocks.TextBlock(rows=2))], label='our processes')))])), ('banner', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('message', wagtail.core.blocks.TextBlock()), ('first_image', wagtail.images.blocks.ImageChooserBlock()), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True),
        ),
    ]
