# Generated by Django 2.0.5 on 2018-07-01 16:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_expertise_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='services',
            field=wagtail.core.fields.StreamField([('services', wagtail.core.blocks.StructBlock([]))], blank=True),
        ),
    ]
