# Generated by Django 2.0.5 on 2018-07-01 21:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_auto_20180701_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about studio page'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'studio contact page'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': 'studio expertise page'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contacts',
            field=wagtail.core.fields.StreamField([('contacts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('category', wagtail.core.blocks.ChoiceBlock(choices=[('email', 'email'), ('phone', 'phone'), ('address', 'address')]))], label='office contact')))], blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subcaption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
