# Generated by Django 2.0.5 on 2018-07-01 21:49

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_auto_20180701_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantactformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form', to='studio.Contact'),
        ),
    ]
