# Generated by Django 2.0.5 on 2018-07-02 13:01

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_auto_20180702_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantactformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_fields', to='studio.Contact'),
        ),
    ]
