# Generated by Django 2.0.5 on 2018-07-02 15:24

import ayira.backend.core.block
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_auto_20180702_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacts',
            field=wagtail.core.fields.StreamField([('contacts', wagtail.core.blocks.StructBlock([('contact', wagtail.core.blocks.ListBlock(ayira.backend.core.block.ContactBlock))], label='office contacts'))], blank=True),
        ),
    ]
