# Generated by Django 2.0.5 on 2018-07-02 16:07

import ayira.backend.core.block
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_auto_20180702_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacts',
            field=wagtail.core.fields.StreamField([('contacts', ayira.backend.core.block.ContactListBlock(wagtail.core.blocks.StructBlock([('category', wagtail.core.blocks.ChoiceBlock(choices=[('email', 'email'), ('phone', 'phone'), ('address', 'address')])), ('info', wagtail.core.blocks.CharBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock())], label='office contacts')))], blank=True),
        ),
    ]
