# Generated by Django 2.0.5 on 2018-07-03 22:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_auto_20180702_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='prices',
        ),
        migrations.AddField(
            model_name='expertise',
            name='plans',
            field=wagtail.core.fields.StreamField([('prices', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('caption', wagtail.core.blocks.CharBlock()), ('plan', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('feature', wagtail.core.blocks.CharBlock()), ('icon', wagtail.core.blocks.CharBlock(help_text='Icons must be a UNCODE character'))], label='Feature'))), ('hire_button', wagtail.snippets.blocks.SnippetChooserBlock('core.Button')), ('customise_button', wagtail.core.blocks.CharBlock(help_text='Customise hire button content'))], label='plan')))]))], blank=True),
        ),
    ]
