# Generated by Django 2.0.5 on 2018-07-04 01:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0021_auto_20180704_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='mvp_plans',
            field=wagtail.core.fields.StreamField([('plans', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('caption', wagtail.core.blocks.CharBlock()), ('plan', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('feature', wagtail.core.blocks.CharBlock()), ('icon', wagtail.core.blocks.CharBlock(default='ti-check', ediatble=False, help_text='Icons must be a UNCODE character'))], label='Feature'))), ('hire_button', wagtail.snippets.blocks.SnippetChooserBlock('core.Button')), ('customise_button', wagtail.core.blocks.CharBlock(help_text='Customise hire button content'))], label='plan')))]))], blank=True),
        ),
    ]
