# Generated by Django 2.0.5 on 2018-07-23 21:46

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0023_auto_20180723_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontentitem',
            name='message',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homecontentitem',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='message',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
