# Generated by Django 2.0.5 on 2018-07-29 23:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0020_add-verbose-name'),
        ('studio', '0024_auto_20180723_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimalisticApp',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_header', models.CharField(blank=True, max_length=255, null=True)),
                ('available_apps', wagtail.core.fields.StreamField([('available_app', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock()), ('store_name', wagtail.core.blocks.CharBlock()), ('app_address', wagtail.core.blocks.URLBlock()), ('store_logo', wagtail.images.blocks.ImageChooserBlock())]))])),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'studio minimalistic app page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
