# Generated by Django 2.0.5 on 2018-07-29 23:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0025_minimalisticapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minimalisticapp',
            options={'verbose_name': 'app cover page'},
        ),
        migrations.AlterField(
            model_name='minimalisticapp',
            name='available_apps',
            field=wagtail.core.fields.StreamField([('available_app', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock()), ('store_name', wagtail.core.blocks.CharBlock()), ('app_address', wagtail.core.blocks.URLBlock()), ('store_logo', wagtail.images.blocks.ImageChooserBlock())]))], blank=True),
        ),
    ]
